#ifndef STACKVM_MATHOPERATION_HPP
#define STACKVM_MATHOPERATION_HPP

#include <cstdint>
#include "Instruction.hpp"

namespace StackVM
{
    class MathOperation
    {
    public:
        static int GetZeroFlag();
        static int GetCompareFlag();
        static void ClearFlags();

        static void Add(Instruction* instruction, byte* lhs, byte* rhs, Type lhsDataType, Type rhsDataType, byte* registers, byte* assemblyData);
        static void Subtract(Instruction* instruction, byte* lhs, byte* rhs, Type lhsDataType, Type rhsDataType, byte* registers, byte* assemblyData);
        static void Multiply(Instruction* instruction, byte* lhs, byte* rhs, Type lhsDataType, Type rhsDataType, byte* registers, byte* assemblyData);
        static void Divide(Instruction* instruction, byte* lhs, byte* rhs, Type lhsDataType, Type rhsDataType, byte* registers, byte* assemblyData);
        static void Compare(Instruction* instruction, byte* lhs, byte* rhs, Type lhsDataType, Type rhsDataType, byte* registers, byte* assemblyData);
    private:
        static int zeroFlag;
        static int compareFlag;
        static void SetFlags(int flagCompare, int flagZero);
        static void Add(unsigned char* lhs, unsigned char* rhs);
        static void Add(unsigned char* lhs, char* rhs);
        static void Add(unsigned char* lhs, uint16_t* rhs);
        static void Add(unsigned char* lhs, int16_t* rhs);
        static void Add(unsigned char* lhs, uint32_t* rhs);
        static void Add(unsigned char* lhs, int32_t* rhs);
        static void Add(unsigned char* lhs, uint64_t* rhs);
        static void Add(unsigned char* lhs, int64_t* rhs);
        static void Add(unsigned char* lhs, float* rhs);
        static void Add(unsigned char* lhs, double* rhs);
        static void Add(char* lhs, unsigned char* rhs);
        static void Add(char* lhs, char* rhs);
        static void Add(char* lhs, uint16_t* rhs);
        static void Add(char* lhs, int16_t* rhs);
        static void Add(char* lhs, uint32_t* rhs);
        static void Add(char* lhs, int32_t* rhs);
        static void Add(char* lhs, uint64_t* rhs);
        static void Add(char* lhs, int64_t* rhs);
        static void Add(char* lhs, float* rhs);
        static void Add(char* lhs, double* rhs);
        static void Add(uint16_t* lhs, unsigned char* rhs);
        static void Add(uint16_t* lhs, char* rhs);
        static void Add(uint16_t* lhs, uint16_t* rhs);
        static void Add(uint16_t* lhs, int16_t* rhs);
        static void Add(uint16_t* lhs, uint32_t* rhs);
        static void Add(uint16_t* lhs, int32_t* rhs);
        static void Add(uint16_t* lhs, uint64_t* rhs);
        static void Add(uint16_t* lhs, int64_t* rhs);
        static void Add(uint16_t* lhs, float* rhs);
        static void Add(uint16_t* lhs, double* rhs);
        static void Add(int16_t* lhs, unsigned char* rhs);
        static void Add(int16_t* lhs, char* rhs);
        static void Add(int16_t* lhs, uint16_t* rhs);
        static void Add(int16_t* lhs, int16_t* rhs);
        static void Add(int16_t* lhs, uint32_t* rhs);
        static void Add(int16_t* lhs, int32_t* rhs);
        static void Add(int16_t* lhs, uint64_t* rhs);
        static void Add(int16_t* lhs, int64_t* rhs);
        static void Add(int16_t* lhs, float* rhs);
        static void Add(int16_t* lhs, double* rhs);
        static void Add(uint32_t* lhs, unsigned char* rhs);
        static void Add(uint32_t* lhs, char* rhs);
        static void Add(uint32_t* lhs, uint16_t* rhs);
        static void Add(uint32_t* lhs, int16_t* rhs);
        static void Add(uint32_t* lhs, uint32_t* rhs);
        static void Add(uint32_t* lhs, int32_t* rhs);
        static void Add(uint32_t* lhs, uint64_t* rhs);
        static void Add(uint32_t* lhs, int64_t* rhs);
        static void Add(uint32_t* lhs, float* rhs);
        static void Add(uint32_t* lhs, double* rhs);
        static void Add(int32_t* lhs, unsigned char* rhs);
        static void Add(int32_t* lhs, char* rhs);
        static void Add(int32_t* lhs, uint16_t* rhs);
        static void Add(int32_t* lhs, int16_t* rhs);
        static void Add(int32_t* lhs, uint32_t* rhs);
        static void Add(int32_t* lhs, int32_t* rhs);
        static void Add(int32_t* lhs, uint64_t* rhs);
        static void Add(int32_t* lhs, int64_t* rhs);
        static void Add(int32_t* lhs, float* rhs);
        static void Add(int32_t* lhs, double* rhs);
        static void Add(uint64_t* lhs, unsigned char* rhs);
        static void Add(uint64_t* lhs, char* rhs);
        static void Add(uint64_t* lhs, uint16_t* rhs);
        static void Add(uint64_t* lhs, int16_t* rhs);
        static void Add(uint64_t* lhs, uint32_t* rhs);
        static void Add(uint64_t* lhs, int32_t* rhs);
        static void Add(uint64_t* lhs, uint64_t* rhs);
        static void Add(uint64_t* lhs, int64_t* rhs);
        static void Add(uint64_t* lhs, float* rhs);
        static void Add(uint64_t* lhs, double* rhs);
        static void Add(int64_t* lhs, unsigned char* rhs);
        static void Add(int64_t* lhs, char* rhs);
        static void Add(int64_t* lhs, uint16_t* rhs);
        static void Add(int64_t* lhs, int16_t* rhs);
        static void Add(int64_t* lhs, uint32_t* rhs);
        static void Add(int64_t* lhs, int32_t* rhs);
        static void Add(int64_t* lhs, uint64_t* rhs);
        static void Add(int64_t* lhs, int64_t* rhs);
        static void Add(int64_t* lhs, float* rhs);
        static void Add(int64_t* lhs, double* rhs);
        static void Add(float* lhs, unsigned char* rhs);
        static void Add(float* lhs, char* rhs);
        static void Add(float* lhs, uint16_t* rhs);
        static void Add(float* lhs, int16_t* rhs);
        static void Add(float* lhs, uint32_t* rhs);
        static void Add(float* lhs, int32_t* rhs);
        static void Add(float* lhs, uint64_t* rhs);
        static void Add(float* lhs, int64_t* rhs);
        static void Add(float* lhs, float* rhs);
        static void Add(float* lhs, double* rhs);
        static void Add(double* lhs, unsigned char* rhs);
        static void Add(double* lhs, char* rhs);
        static void Add(double* lhs, uint16_t* rhs);
        static void Add(double* lhs, int16_t* rhs);
        static void Add(double* lhs, uint32_t* rhs);
        static void Add(double* lhs, int32_t* rhs);
        static void Add(double* lhs, uint64_t* rhs);
        static void Add(double* lhs, int64_t* rhs);
        static void Add(double* lhs, float* rhs);
        static void Add(double* lhs, double* rhs);

        static void Subtract(unsigned char* lhs, unsigned char* rhs);
        static void Subtract(unsigned char* lhs, char* rhs);
        static void Subtract(unsigned char* lhs, uint16_t* rhs);
        static void Subtract(unsigned char* lhs, int16_t* rhs);
        static void Subtract(unsigned char* lhs, uint32_t* rhs);
        static void Subtract(unsigned char* lhs, int32_t* rhs);
        static void Subtract(unsigned char* lhs, uint64_t* rhs);
        static void Subtract(unsigned char* lhs, int64_t* rhs);
        static void Subtract(unsigned char* lhs, float* rhs);
        static void Subtract(unsigned char* lhs, double* rhs);
        static void Subtract(char* lhs, unsigned char* rhs);
        static void Subtract(char* lhs, char* rhs);
        static void Subtract(char* lhs, uint16_t* rhs);
        static void Subtract(char* lhs, int16_t* rhs);
        static void Subtract(char* lhs, uint32_t* rhs);
        static void Subtract(char* lhs, int32_t* rhs);
        static void Subtract(char* lhs, uint64_t* rhs);
        static void Subtract(char* lhs, int64_t* rhs);
        static void Subtract(char* lhs, float* rhs);
        static void Subtract(char* lhs, double* rhs);
        static void Subtract(uint16_t* lhs, unsigned char* rhs);
        static void Subtract(uint16_t* lhs, char* rhs);
        static void Subtract(uint16_t* lhs, uint16_t* rhs);
        static void Subtract(uint16_t* lhs, int16_t* rhs);
        static void Subtract(uint16_t* lhs, uint32_t* rhs);
        static void Subtract(uint16_t* lhs, int32_t* rhs);
        static void Subtract(uint16_t* lhs, uint64_t* rhs);
        static void Subtract(uint16_t* lhs, int64_t* rhs);
        static void Subtract(uint16_t* lhs, float* rhs);
        static void Subtract(uint16_t* lhs, double* rhs);
        static void Subtract(int16_t* lhs, unsigned char* rhs);
        static void Subtract(int16_t* lhs, char* rhs);
        static void Subtract(int16_t* lhs, uint16_t* rhs);
        static void Subtract(int16_t* lhs, int16_t* rhs);
        static void Subtract(int16_t* lhs, uint32_t* rhs);
        static void Subtract(int16_t* lhs, int32_t* rhs);
        static void Subtract(int16_t* lhs, uint64_t* rhs);
        static void Subtract(int16_t* lhs, int64_t* rhs);
        static void Subtract(int16_t* lhs, float* rhs);
        static void Subtract(int16_t* lhs, double* rhs);
        static void Subtract(uint32_t* lhs, unsigned char* rhs);
        static void Subtract(uint32_t* lhs, char* rhs);
        static void Subtract(uint32_t* lhs, uint16_t* rhs);
        static void Subtract(uint32_t* lhs, int16_t* rhs);
        static void Subtract(uint32_t* lhs, uint32_t* rhs);
        static void Subtract(uint32_t* lhs, int32_t* rhs);
        static void Subtract(uint32_t* lhs, uint64_t* rhs);
        static void Subtract(uint32_t* lhs, int64_t* rhs);
        static void Subtract(uint32_t* lhs, float* rhs);
        static void Subtract(uint32_t* lhs, double* rhs);
        static void Subtract(int32_t* lhs, unsigned char* rhs);
        static void Subtract(int32_t* lhs, char* rhs);
        static void Subtract(int32_t* lhs, uint16_t* rhs);
        static void Subtract(int32_t* lhs, int16_t* rhs);
        static void Subtract(int32_t* lhs, uint32_t* rhs);
        static void Subtract(int32_t* lhs, int32_t* rhs);
        static void Subtract(int32_t* lhs, uint64_t* rhs);
        static void Subtract(int32_t* lhs, int64_t* rhs);
        static void Subtract(int32_t* lhs, float* rhs);
        static void Subtract(int32_t* lhs, double* rhs);
        static void Subtract(uint64_t* lhs, unsigned char* rhs);
        static void Subtract(uint64_t* lhs, char* rhs);
        static void Subtract(uint64_t* lhs, uint16_t* rhs);
        static void Subtract(uint64_t* lhs, int16_t* rhs);
        static void Subtract(uint64_t* lhs, uint32_t* rhs);
        static void Subtract(uint64_t* lhs, int32_t* rhs);
        static void Subtract(uint64_t* lhs, uint64_t* rhs);
        static void Subtract(uint64_t* lhs, int64_t* rhs);
        static void Subtract(uint64_t* lhs, float* rhs);
        static void Subtract(uint64_t* lhs, double* rhs);
        static void Subtract(int64_t* lhs, unsigned char* rhs);
        static void Subtract(int64_t* lhs, char* rhs);
        static void Subtract(int64_t* lhs, uint16_t* rhs);
        static void Subtract(int64_t* lhs, int16_t* rhs);
        static void Subtract(int64_t* lhs, uint32_t* rhs);
        static void Subtract(int64_t* lhs, int32_t* rhs);
        static void Subtract(int64_t* lhs, uint64_t* rhs);
        static void Subtract(int64_t* lhs, int64_t* rhs);
        static void Subtract(int64_t* lhs, float* rhs);
        static void Subtract(int64_t* lhs, double* rhs);
        static void Subtract(float* lhs, unsigned char* rhs);
        static void Subtract(float* lhs, char* rhs);
        static void Subtract(float* lhs, uint16_t* rhs);
        static void Subtract(float* lhs, int16_t* rhs);
        static void Subtract(float* lhs, uint32_t* rhs);
        static void Subtract(float* lhs, int32_t* rhs);
        static void Subtract(float* lhs, uint64_t* rhs);
        static void Subtract(float* lhs, int64_t* rhs);
        static void Subtract(float* lhs, float* rhs);
        static void Subtract(float* lhs, double* rhs);
        static void Subtract(double* lhs, unsigned char* rhs);
        static void Subtract(double* lhs, char* rhs);
        static void Subtract(double* lhs, uint16_t* rhs);
        static void Subtract(double* lhs, int16_t* rhs);
        static void Subtract(double* lhs, uint32_t* rhs);
        static void Subtract(double* lhs, int32_t* rhs);
        static void Subtract(double* lhs, uint64_t* rhs);
        static void Subtract(double* lhs, int64_t* rhs);
        static void Subtract(double* lhs, float* rhs);
        static void Subtract(double* lhs, double* rhs);

        static void Multiply(unsigned char* lhs, unsigned char* rhs);
        static void Multiply(unsigned char* lhs, char* rhs);
        static void Multiply(unsigned char* lhs, uint16_t* rhs);
        static void Multiply(unsigned char* lhs, int16_t* rhs);
        static void Multiply(unsigned char* lhs, uint32_t* rhs);
        static void Multiply(unsigned char* lhs, int32_t* rhs);
        static void Multiply(unsigned char* lhs, uint64_t* rhs);
        static void Multiply(unsigned char* lhs, int64_t* rhs);
        static void Multiply(unsigned char* lhs, float* rhs);
        static void Multiply(unsigned char* lhs, double* rhs);
        static void Multiply(char* lhs, unsigned char* rhs);
        static void Multiply(char* lhs, char* rhs);
        static void Multiply(char* lhs, uint16_t* rhs);
        static void Multiply(char* lhs, int16_t* rhs);
        static void Multiply(char* lhs, uint32_t* rhs);
        static void Multiply(char* lhs, int32_t* rhs);
        static void Multiply(char* lhs, uint64_t* rhs);
        static void Multiply(char* lhs, int64_t* rhs);
        static void Multiply(char* lhs, float* rhs);
        static void Multiply(char* lhs, double* rhs);
        static void Multiply(uint16_t* lhs, unsigned char* rhs);
        static void Multiply(uint16_t* lhs, char* rhs);
        static void Multiply(uint16_t* lhs, uint16_t* rhs);
        static void Multiply(uint16_t* lhs, int16_t* rhs);
        static void Multiply(uint16_t* lhs, uint32_t* rhs);
        static void Multiply(uint16_t* lhs, int32_t* rhs);
        static void Multiply(uint16_t* lhs, uint64_t* rhs);
        static void Multiply(uint16_t* lhs, int64_t* rhs);
        static void Multiply(uint16_t* lhs, float* rhs);
        static void Multiply(uint16_t* lhs, double* rhs);
        static void Multiply(int16_t* lhs, unsigned char* rhs);
        static void Multiply(int16_t* lhs, char* rhs);
        static void Multiply(int16_t* lhs, uint16_t* rhs);
        static void Multiply(int16_t* lhs, int16_t* rhs);
        static void Multiply(int16_t* lhs, uint32_t* rhs);
        static void Multiply(int16_t* lhs, int32_t* rhs);
        static void Multiply(int16_t* lhs, uint64_t* rhs);
        static void Multiply(int16_t* lhs, int64_t* rhs);
        static void Multiply(int16_t* lhs, float* rhs);
        static void Multiply(int16_t* lhs, double* rhs);
        static void Multiply(uint32_t* lhs, unsigned char* rhs);
        static void Multiply(uint32_t* lhs, char* rhs);
        static void Multiply(uint32_t* lhs, uint16_t* rhs);
        static void Multiply(uint32_t* lhs, int16_t* rhs);
        static void Multiply(uint32_t* lhs, uint32_t* rhs);
        static void Multiply(uint32_t* lhs, int32_t* rhs);
        static void Multiply(uint32_t* lhs, uint64_t* rhs);
        static void Multiply(uint32_t* lhs, int64_t* rhs);
        static void Multiply(uint32_t* lhs, float* rhs);
        static void Multiply(uint32_t* lhs, double* rhs);
        static void Multiply(int32_t* lhs, unsigned char* rhs);
        static void Multiply(int32_t* lhs, char* rhs);
        static void Multiply(int32_t* lhs, uint16_t* rhs);
        static void Multiply(int32_t* lhs, int16_t* rhs);
        static void Multiply(int32_t* lhs, uint32_t* rhs);
        static void Multiply(int32_t* lhs, int32_t* rhs);
        static void Multiply(int32_t* lhs, uint64_t* rhs);
        static void Multiply(int32_t* lhs, int64_t* rhs);
        static void Multiply(int32_t* lhs, float* rhs);
        static void Multiply(int32_t* lhs, double* rhs);
        static void Multiply(uint64_t* lhs, unsigned char* rhs);
        static void Multiply(uint64_t* lhs, char* rhs);
        static void Multiply(uint64_t* lhs, uint16_t* rhs);
        static void Multiply(uint64_t* lhs, int16_t* rhs);
        static void Multiply(uint64_t* lhs, uint32_t* rhs);
        static void Multiply(uint64_t* lhs, int32_t* rhs);
        static void Multiply(uint64_t* lhs, uint64_t* rhs);
        static void Multiply(uint64_t* lhs, int64_t* rhs);
        static void Multiply(uint64_t* lhs, float* rhs);
        static void Multiply(uint64_t* lhs, double* rhs);
        static void Multiply(int64_t* lhs, unsigned char* rhs);
        static void Multiply(int64_t* lhs, char* rhs);
        static void Multiply(int64_t* lhs, uint16_t* rhs);
        static void Multiply(int64_t* lhs, int16_t* rhs);
        static void Multiply(int64_t* lhs, uint32_t* rhs);
        static void Multiply(int64_t* lhs, int32_t* rhs);
        static void Multiply(int64_t* lhs, uint64_t* rhs);
        static void Multiply(int64_t* lhs, int64_t* rhs);
        static void Multiply(int64_t* lhs, float* rhs);
        static void Multiply(int64_t* lhs, double* rhs);
        static void Multiply(float* lhs, unsigned char* rhs);
        static void Multiply(float* lhs, char* rhs);
        static void Multiply(float* lhs, uint16_t* rhs);
        static void Multiply(float* lhs, int16_t* rhs);
        static void Multiply(float* lhs, uint32_t* rhs);
        static void Multiply(float* lhs, int32_t* rhs);
        static void Multiply(float* lhs, uint64_t* rhs);
        static void Multiply(float* lhs, int64_t* rhs);
        static void Multiply(float* lhs, float* rhs);
        static void Multiply(float* lhs, double* rhs);
        static void Multiply(double* lhs, unsigned char* rhs);
        static void Multiply(double* lhs, char* rhs);
        static void Multiply(double* lhs, uint16_t* rhs);
        static void Multiply(double* lhs, int16_t* rhs);
        static void Multiply(double* lhs, uint32_t* rhs);
        static void Multiply(double* lhs, int32_t* rhs);
        static void Multiply(double* lhs, uint64_t* rhs);
        static void Multiply(double* lhs, int64_t* rhs);
        static void Multiply(double* lhs, float* rhs);
        static void Multiply(double* lhs, double* rhs);

        static void Divide(unsigned char* lhs, unsigned char* rhs);
        static void Divide(unsigned char* lhs, char* rhs);
        static void Divide(unsigned char* lhs, uint16_t* rhs);
        static void Divide(unsigned char* lhs, int16_t* rhs);
        static void Divide(unsigned char* lhs, uint32_t* rhs);
        static void Divide(unsigned char* lhs, int32_t* rhs);
        static void Divide(unsigned char* lhs, uint64_t* rhs);
        static void Divide(unsigned char* lhs, int64_t* rhs);
        static void Divide(unsigned char* lhs, float* rhs);
        static void Divide(unsigned char* lhs, double* rhs);
        static void Divide(char* lhs, unsigned char* rhs);
        static void Divide(char* lhs, char* rhs);
        static void Divide(char* lhs, uint16_t* rhs);
        static void Divide(char* lhs, int16_t* rhs);
        static void Divide(char* lhs, uint32_t* rhs);
        static void Divide(char* lhs, int32_t* rhs);
        static void Divide(char* lhs, uint64_t* rhs);
        static void Divide(char* lhs, int64_t* rhs);
        static void Divide(char* lhs, float* rhs);
        static void Divide(char* lhs, double* rhs);
        static void Divide(uint16_t* lhs, unsigned char* rhs);
        static void Divide(uint16_t* lhs, char* rhs);
        static void Divide(uint16_t* lhs, uint16_t* rhs);
        static void Divide(uint16_t* lhs, int16_t* rhs);
        static void Divide(uint16_t* lhs, uint32_t* rhs);
        static void Divide(uint16_t* lhs, int32_t* rhs);
        static void Divide(uint16_t* lhs, uint64_t* rhs);
        static void Divide(uint16_t* lhs, int64_t* rhs);
        static void Divide(uint16_t* lhs, float* rhs);
        static void Divide(uint16_t* lhs, double* rhs);
        static void Divide(int16_t* lhs, unsigned char* rhs);
        static void Divide(int16_t* lhs, char* rhs);
        static void Divide(int16_t* lhs, uint16_t* rhs);
        static void Divide(int16_t* lhs, int16_t* rhs);
        static void Divide(int16_t* lhs, uint32_t* rhs);
        static void Divide(int16_t* lhs, int32_t* rhs);
        static void Divide(int16_t* lhs, uint64_t* rhs);
        static void Divide(int16_t* lhs, int64_t* rhs);
        static void Divide(int16_t* lhs, float* rhs);
        static void Divide(int16_t* lhs, double* rhs);
        static void Divide(uint32_t* lhs, unsigned char* rhs);
        static void Divide(uint32_t* lhs, char* rhs);
        static void Divide(uint32_t* lhs, uint16_t* rhs);
        static void Divide(uint32_t* lhs, int16_t* rhs);
        static void Divide(uint32_t* lhs, uint32_t* rhs);
        static void Divide(uint32_t* lhs, int32_t* rhs);
        static void Divide(uint32_t* lhs, uint64_t* rhs);
        static void Divide(uint32_t* lhs, int64_t* rhs);
        static void Divide(uint32_t* lhs, float* rhs);
        static void Divide(uint32_t* lhs, double* rhs);
        static void Divide(int32_t* lhs, unsigned char* rhs);
        static void Divide(int32_t* lhs, char* rhs);
        static void Divide(int32_t* lhs, uint16_t* rhs);
        static void Divide(int32_t* lhs, int16_t* rhs);
        static void Divide(int32_t* lhs, uint32_t* rhs);
        static void Divide(int32_t* lhs, int32_t* rhs);
        static void Divide(int32_t* lhs, uint64_t* rhs);
        static void Divide(int32_t* lhs, int64_t* rhs);
        static void Divide(int32_t* lhs, float* rhs);
        static void Divide(int32_t* lhs, double* rhs);
        static void Divide(uint64_t* lhs, unsigned char* rhs);
        static void Divide(uint64_t* lhs, char* rhs);
        static void Divide(uint64_t* lhs, uint16_t* rhs);
        static void Divide(uint64_t* lhs, int16_t* rhs);
        static void Divide(uint64_t* lhs, uint32_t* rhs);
        static void Divide(uint64_t* lhs, int32_t* rhs);
        static void Divide(uint64_t* lhs, uint64_t* rhs);
        static void Divide(uint64_t* lhs, int64_t* rhs);
        static void Divide(uint64_t* lhs, float* rhs);
        static void Divide(uint64_t* lhs, double* rhs);
        static void Divide(int64_t* lhs, unsigned char* rhs);
        static void Divide(int64_t* lhs, char* rhs);
        static void Divide(int64_t* lhs, uint16_t* rhs);
        static void Divide(int64_t* lhs, int16_t* rhs);
        static void Divide(int64_t* lhs, uint32_t* rhs);
        static void Divide(int64_t* lhs, int32_t* rhs);
        static void Divide(int64_t* lhs, uint64_t* rhs);
        static void Divide(int64_t* lhs, int64_t* rhs);
        static void Divide(int64_t* lhs, float* rhs);
        static void Divide(int64_t* lhs, double* rhs);
        static void Divide(float* lhs, unsigned char* rhs);
        static void Divide(float* lhs, char* rhs);
        static void Divide(float* lhs, uint16_t* rhs);
        static void Divide(float* lhs, int16_t* rhs);
        static void Divide(float* lhs, uint32_t* rhs);
        static void Divide(float* lhs, int32_t* rhs);
        static void Divide(float* lhs, uint64_t* rhs);
        static void Divide(float* lhs, int64_t* rhs);
        static void Divide(float* lhs, float* rhs);
        static void Divide(float* lhs, double* rhs);
        static void Divide(double* lhs, unsigned char* rhs);
        static void Divide(double* lhs, char* rhs);
        static void Divide(double* lhs, uint16_t* rhs);
        static void Divide(double* lhs, int16_t* rhs);
        static void Divide(double* lhs, uint32_t* rhs);
        static void Divide(double* lhs, int32_t* rhs);
        static void Divide(double* lhs, uint64_t* rhs);
        static void Divide(double* lhs, int64_t* rhs);
        static void Divide(double* lhs, float* rhs);
        static void Divide(double* lhs, double* rhs);
        
        static int64_t Compare(unsigned char* lhs, unsigned char* rhs);
        static int64_t Compare(unsigned char* lhs, char* rhs);
        static int64_t Compare(unsigned char* lhs, uint16_t* rhs);
        static int64_t Compare(unsigned char* lhs, int16_t* rhs);
        static int64_t Compare(unsigned char* lhs, uint32_t* rhs);
        static int64_t Compare(unsigned char* lhs, int32_t* rhs);
        static int64_t Compare(unsigned char* lhs, uint64_t* rhs);
        static int64_t Compare(unsigned char* lhs, int64_t* rhs);
        static int64_t Compare(unsigned char* lhs, float* rhs);
        static int64_t Compare(unsigned char* lhs, double* rhs);
        static int64_t Compare(char* lhs, unsigned char* rhs);
        static int64_t Compare(char* lhs, char* rhs);
        static int64_t Compare(char* lhs, uint16_t* rhs);
        static int64_t Compare(char* lhs, int16_t* rhs);
        static int64_t Compare(char* lhs, uint32_t* rhs);
        static int64_t Compare(char* lhs, int32_t* rhs);
        static int64_t Compare(char* lhs, uint64_t* rhs);
        static int64_t Compare(char* lhs, int64_t* rhs);
        static int64_t Compare(char* lhs, float* rhs);
        static int64_t Compare(char* lhs, double* rhs);
        static int64_t Compare(uint16_t* lhs, unsigned char* rhs);
        static int64_t Compare(uint16_t* lhs, char* rhs);
        static int64_t Compare(uint16_t* lhs, uint16_t* rhs);
        static int64_t Compare(uint16_t* lhs, int16_t* rhs);
        static int64_t Compare(uint16_t* lhs, uint32_t* rhs);
        static int64_t Compare(uint16_t* lhs, int32_t* rhs);
        static int64_t Compare(uint16_t* lhs, uint64_t* rhs);
        static int64_t Compare(uint16_t* lhs, int64_t* rhs);
        static int64_t Compare(uint16_t* lhs, float* rhs);
        static int64_t Compare(uint16_t* lhs, double* rhs);
        static int64_t Compare(int16_t* lhs, unsigned char* rhs);
        static int64_t Compare(int16_t* lhs, char* rhs);
        static int64_t Compare(int16_t* lhs, uint16_t* rhs);
        static int64_t Compare(int16_t* lhs, int16_t* rhs);
        static int64_t Compare(int16_t* lhs, uint32_t* rhs);
        static int64_t Compare(int16_t* lhs, int32_t* rhs);
        static int64_t Compare(int16_t* lhs, uint64_t* rhs);
        static int64_t Compare(int16_t* lhs, int64_t* rhs);
        static int64_t Compare(int16_t* lhs, float* rhs);
        static int64_t Compare(int16_t* lhs, double* rhs);
        static int64_t Compare(uint32_t* lhs, unsigned char* rhs);
        static int64_t Compare(uint32_t* lhs, char* rhs);
        static int64_t Compare(uint32_t* lhs, uint16_t* rhs);
        static int64_t Compare(uint32_t* lhs, int16_t* rhs);
        static int64_t Compare(uint32_t* lhs, uint32_t* rhs);
        static int64_t Compare(uint32_t* lhs, int32_t* rhs);
        static int64_t Compare(uint32_t* lhs, uint64_t* rhs);
        static int64_t Compare(uint32_t* lhs, int64_t* rhs);
        static int64_t Compare(uint32_t* lhs, float* rhs);
        static int64_t Compare(uint32_t* lhs, double* rhs);
        static int64_t Compare(int32_t* lhs, unsigned char* rhs);
        static int64_t Compare(int32_t* lhs, char* rhs);
        static int64_t Compare(int32_t* lhs, uint16_t* rhs);
        static int64_t Compare(int32_t* lhs, int16_t* rhs);
        static int64_t Compare(int32_t* lhs, uint32_t* rhs);
        static int64_t Compare(int32_t* lhs, int32_t* rhs);
        static int64_t Compare(int32_t* lhs, uint64_t* rhs);
        static int64_t Compare(int32_t* lhs, int64_t* rhs);
        static int64_t Compare(int32_t* lhs, float* rhs);
        static int64_t Compare(int32_t* lhs, double* rhs);
        static int64_t Compare(uint64_t* lhs, unsigned char* rhs);
        static int64_t Compare(uint64_t* lhs, char* rhs);
        static int64_t Compare(uint64_t* lhs, uint16_t* rhs);
        static int64_t Compare(uint64_t* lhs, int16_t* rhs);
        static int64_t Compare(uint64_t* lhs, uint32_t* rhs);
        static int64_t Compare(uint64_t* lhs, int32_t* rhs);
        static int64_t Compare(uint64_t* lhs, uint64_t* rhs);
        static int64_t Compare(uint64_t* lhs, int64_t* rhs);
        static int64_t Compare(uint64_t* lhs, float* rhs);
        static int64_t Compare(uint64_t* lhs, double* rhs);
        static int64_t Compare(int64_t* lhs, unsigned char* rhs);
        static int64_t Compare(int64_t* lhs, char* rhs);
        static int64_t Compare(int64_t* lhs, uint16_t* rhs);
        static int64_t Compare(int64_t* lhs, int16_t* rhs);
        static int64_t Compare(int64_t* lhs, uint32_t* rhs);
        static int64_t Compare(int64_t* lhs, int32_t* rhs);
        static int64_t Compare(int64_t* lhs, uint64_t* rhs);
        static int64_t Compare(int64_t* lhs, int64_t* rhs);
        static int64_t Compare(int64_t* lhs, float* rhs);
        static int64_t Compare(int64_t* lhs, double* rhs);
        static int64_t Compare(float* lhs, unsigned char* rhs);
        static int64_t Compare(float* lhs, char* rhs);
        static int64_t Compare(float* lhs, uint16_t* rhs);
        static int64_t Compare(float* lhs, int16_t* rhs);
        static int64_t Compare(float* lhs, uint32_t* rhs);
        static int64_t Compare(float* lhs, int32_t* rhs);
        static int64_t Compare(float* lhs, uint64_t* rhs);
        static int64_t Compare(float* lhs, int64_t* rhs);
        static int64_t Compare(float* lhs, float* rhs);
        static int64_t Compare(float* lhs, double* rhs);
        static int64_t Compare(double* lhs, unsigned char* rhs);
        static int64_t Compare(double* lhs, char* rhs);
        static int64_t Compare(double* lhs, uint16_t* rhs);
        static int64_t Compare(double* lhs, int16_t* rhs);
        static int64_t Compare(double* lhs, uint32_t* rhs);
        static int64_t Compare(double* lhs, int32_t* rhs);
        static int64_t Compare(double* lhs, uint64_t* rhs);
        static int64_t Compare(double* lhs, int64_t* rhs);
        static int64_t Compare(double* lhs, float* rhs);
        static int64_t Compare(double* lhs, double* rhs);        
    };
};

#endif